---
  - name: Update apt-cache.
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 7200
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install build tools.
    ansible.builtin.apt:
      name: ['gcc', 'g++', 'make', 'cmake', 'build-essential', 'git',
        'autoconf', 'curl', 'libtool', 'libssl-dev', 'libcurl4-openssl-dev',
        'libz-dev', 'systemd-coredump', 'liblz4-tool']
      state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install build tools.
    ansible.builtin.apt:
      name: ['gcc', 'g++', 'make', 'cmake', 'build-essential', 'git',
        'cmake', 'autoconf', 'curl', 'libtool', 'libssl-dev', 'libcurl4-openssl-dev',
        'libz-dev']
      state: latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: Install libtool-bin.
    ansible.builtin.apt:
      name: libtool-bin
      state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    ignore_errors: yes

  - name: Install and configure voipmonitor.
    include_tasks: voipmonitor.yaml
    when: voipmonitorSSLKeyLoggerEnabled

  - name: Check if drachtio-server directory exists.
    ansible.builtin.stat:
      path: /usr/local/src/drachtio-server
    register: drachtio_server

  - name: Make source directory writeable.
    ansible.builtin.file:
      path: /usr/local/src
      state: directory
      mode: 0777
    when: not drachtio_server.stat.exists

  # - name: Get the current github tag version
  #   ansible.builtin.shell: git describe --tags
  #   args:
  #     chdir: /usr/local/src/drachtio-server
  #   register: tag_version.stdout
  #   when: drachtio_server.stat.exists

  - name: Check out drachtio-server.
    ansible.builtin.git:
      repo: https://github.com/davehorton/drachtio-server.git
      dest: /usr/local/src/drachtio-server
      version: "{{drachtioBranch}}"
      depth: 50
      accept_hostkey: yes
      force: yes
    become: no

  - name: Remove build directory from drachtio source
    ansible.builtin.file:
      path: /usr/local/src/drachtio-server/build/
      state: absent
    become: yes

  - name: Build drachtio-server.
    ansible.builtin.shell: ./autogen.sh && mkdir -p build && cd $_ && ../configure CPPFLAGS='-DNDEBUG' && make && make install
    become: yes
    args:
      executable: /bin/bash
      chdir: /usr/local/src/drachtio-server/
      creates: /usr/local/src/drachtio-server/build/drachtio
    notify: restart drachtio

  - name: Create drachtio directories.
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ drachtioConfigDirectory }}"
      - "{{ drachtioLogFileDirectory }}"
      - "{{ drachtioLogArchiveDirectory }}"

  - name: Create drachtio config file
    ansible.builtin.template:
      src: drachtio.conf.xml.j2
      dest: "{{ drachtioConfigDirectory }}/drachtio.conf.xml"
      mode: 0644
      owner: root
      group: root
    notify: restart drachtio

  - name: Create systemd unit file
    ansible.builtin.template:
      src: drachtio-systemd-script.j2
      dest: /etc/systemd/system/drachtio.service
      mode: 0644
      owner: root
      group: root
    notify: restart drachtio
    when: ansible_service_mgr == 'systemd'

  - name: systemctl daemon-reload
    ansible.builtin.shell: systemctl daemon-reload
    when: ansible_service_mgr == 'systemd'

  - name: remove source code
    ansible.builtin.file:
      path: /usr/local/src/drachtio-server
      state: absent
    when: remove_source|bool

