---
- name: Converge
  hosts: all
  become: true
  vars:
    drachtioEnvironment: test
    voipmonitorSSLKeyLoggerEnabled: true
    drachtioTlsEnabled: false

  tasks:

    - name: Update apt cache (on Ubuntu)
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: "Include drachtio role"
      include_role:
        name: "drachtio"
